[package]
name = "sist"
version = "2.0.0"
authors = ["kmgy <bhnk1270223@gn.iwasaki.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "3.3.0"
clap = "2.33.1"
