[package]
name = "sist"
version = "2.0.0"
authors = ["kmgy <bhnk1270223@gn.iwasaki.ac.jp>"]
edition = "2018"
description = "Serial console color syntax for Network devices"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "3.3.0"
clap = "2.33.1"
getch = "0.2.1"
regex = "1.3.7"
chrono = "0.4.11"
