#
#  POSIX Extended Regular Expression Syntax
#  Blanks can not be colored.
#
#  colorings = [
#      [COLOR, REGEX],
#      [COLOR, REGEX],
#      ...
#  ]
#
#  If the color length is 6 => 24bit color (000000-FFFFFF)
#  If the color length is 3 =>  8bit color (000-255)
#
#  Color example
#   * RED           [Uppercase]
#   * 001           [Decimal number]
#   * FF0000        [Hexadecimal]
#   * (255, 0, 0)   [Decimal number]
#
#  Predefined colors
#   * BLACK
#   * RED
#   * GREEN
#   * YELLOW
#   * BLUE
#   * MAGENTA
#   * CYAN
#   * WHITE
#


# port  = "/dev/ttyS0"
# speed = "9600"

colorings = [
    # positive
    ["GREEN", "^(up|enable|enabled|active)$"],

    # string
    ["YELLOW", "^(\"*\"|'*')$"],

    # emphansis
    ["MAGENTA", "^(no|not|confirm|warning|warnings|failed|failures|error|errors|crash)$"],

    # interface
    ["CYAN", "^((Tengigabit|Gigabit|Fast)?Ethernet|(Fa|Gi)).*"],

    # action
    ["RED", "^(disable|disabled|deny|shutdown|down|administratively|none)$"],

    # ipv4_net
    ["GREEN", "^(2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[1-8])[.]((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])[.]){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])$"],

    # ipv4_sub
    ["BLUE" , "^((25[0-5]|24[89])[.])((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])[.]){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])$"],

    # ipv4_wild
    ["MAGENTA", "^(0[.])((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])[.]){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])$"],
]

