#
#  sisterm setting file
#
#  Regular expressions support RE2 Syntax
#
#  [[colorings]]
#  color = "String"       # required
#  regex = "String"       # required
#  underlined = Boolean   # option
#
#  Color example
#   * RED           [Uppercase]
#   * 001           [Decimal number]
#   * FF0000        [Hexadecimal]
#   * (255, 0, 0)   [Decimal number]
#
#  Predefined colors
#   * BLACK
#   * RED
#   * GREEN
#   * YELLOW
#   * BLUE
#   * MAGENTA
#   * CYAN
#   * WHITE
#


# port  = "/dev/ttyS0"
# speed = "9600"

# timestamp
[[colorings]]
color = ""  # no-color
regex = "(\\[.*)|(.*\\])"

# positive
[[colorings]]
color = "GREEN"
regex = "^(yes|YES|up|enable|enabled|active)$"

# string
[[colorings]]
color = "184"
regex = "(\".*\")|('.*')"

# emphansis
[[colorings]]
color = "MAGENTA"
regex = "^(no|NO|not|confirm|warning|warnings|failed|failures|error|errors|crash)$"

# interface
[[colorings]]
color = "CYAN"
regex = "^((Tengigabit|Gigabit|Fast)?Ethernet|(Fa|Gi)).*"

# negative
[[colorings]]
underlined = true
color = "RED"
regex = "^(unassigned|disable|disabled|deny|shutdown|down|administratively|none)$"

# ipv4_net
[[colorings]]
color = "YELLOW"
regex = "^(2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[1-8])[.]((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])[.]){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])$"

# ipv4_sub
[[colorings]]
color = "BLUE"
regex = "^((25[0-5]|24[89])[.])((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])[.]){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])$"

# ipv4_wild
[[colorings]]
color = "MAGENTA"
regex = "^(0[.])((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])[.]){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])$"

