name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: prepare
      run: |
          sudo apt update
          sudo apt install -y pkg-config libudev-dev

    - name: Build
      run: cargo build --verbose --all-targets

    - name: Run tests
      run: cargo test --verbose

    - name: clippy
      run: cargo clippy --all-targets --all-features -- -W clippy::dbg_macro
